name: PlayerTags
version: 1.0.1
main: sys\jordan\tags\PlayerTagsBase
api:
  - 3.0.0
author: sylvrs
softdepend:
  - CombatLogger
  - EconomyAPI
  - FactionsPro
  - PiggyFactions
  - PurePerms
  - RankUp
  - RedSkyBlock